"""baseline_agents_transactions

Revision ID: a5e9a8305f40
Revises: 
Create Date: 2026-04-30 23:14:47.981053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e9a8305f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_agent_id', sa.Uuid(), nullable=False),
    sa.Column('to_agent_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'CONFIRMED', 'SETTLED', 'FAILED', 'ROLLED_BACK', name='transaction_status'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_from_agent_id'), 'transactions', ['from_agent_id'], unique=False)
    op.create_index('ix_transactions_from_agent_id_status', 'transactions', ['from_agent_id', 'status'], unique=False)
    op.create_index('ix_transactions_status_created_at', 'transactions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_to_agent_id'), 'transactions', ['to_agent_id'], unique=False)
    op.create_index('ix_transactions_to_agent_id_status', 'transactions', ['to_agent_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_to_agent_id_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_agent_id'), table_name='transactions')
    op.drop_index('ix_transactions_status_created_at', table_name='transactions')
    op.drop_index('ix_transactions_from_agent_id_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_agent_id'), table_name='transactions')
    op.drop_table('transactions')
    # Di PostgreSQL tipe ENUM transaction_status harus dihapus setelah tabel transactions
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="transaction_status").drop(bind, checkfirst=True)
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
